services:
  backend:
    build:
      context: .
    container_name: ai-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    dns:
      - 8.8.8.8  # ✅ Add this line to fix DNS resolution
