# docker-compose.yml

version: "3.9"

services:
  backend:
    build:
      context: ./apps/backend
    container_name: ai-backend
    ports:
      - "8000:8000"
    env_file:
      - ./apps/backend/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
